// purify.js — tube sort for muddy batches (pure, JSON-serializable state).
// Implements docs/DESIGN.md "Active play › Purifying (tube sort)", ARCHITECTURE.md
// "Puzzles" and docs/V02-CONTRACTS.md "Purify": the size comes from the
// difficulty tier she picks (Relaxed 4 colors / 6 tubes with a free extra tube,
// Steady 6 / 8, Tricky 8 / 10, Master 9 / 11), generated by REVERSE pours from
// a solved state so every puzzle is solvable; unlimited undo. Solved means
// every non-empty tube is one color AND full (corked).
//
// Tubes are arrays of color indices, bottom -> top. A forward pour moves the
// whole contiguous top run of the source as far as the target has room, onto
// an empty tube or a matching top color.
//
// Solvability: each reverse pour takes k units of color c off tube A and
// stacks them on tube B, and is only allowed when the matching forward pour
// B -> A is legal afterwards (A is empty or still topped by c) and moves
// exactly k units back (B's new top run is exactly k long, or A has exactly k
// free slots). Undoing the reverse pours in order therefore solves the puzzle.
// The start is CAPACITY units of each color in its own tube, so undoing them
// reaches the strict solved state (every tube full and uniform), not just a
// "sorted but split" one.

import {
  hexToRgb, rgbToHex, oklchToHex, clampToGamut, deltaEHex,
} from '../color.js';
import { shuffle, pick } from '../rng.js';

export const MIN_COLORS = 4;
export const MAX_COLORS = 9;
export const CAPACITY = 4;

/**
 * Difficulty tiers (all free; docs/PLAN-v0.2.md Theme C.3). `purity` is what a
 * solve sets the batch to; `k` is the puzzle reward in minutes of production
 * (economy.puzzleReward); `minutes` is the expected length shown on the tier
 * control ("about 1 / 2 / 3 / 5 min").
 */
export const TIERS = Object.freeze({
  relaxed: Object.freeze({ colors: 4, tubes: 6, extraTube: true, purity: 'pure', k: 4, minutes: 1 }),
  steady: Object.freeze({ colors: 6, tubes: 8, extraTube: false, purity: 'pure', k: 6, minutes: 2 }),
  tricky: Object.freeze({ colors: 8, tubes: 10, extraTube: false, purity: 'flawless', k: 10, minutes: 3 }),
  master: Object.freeze({ colors: 9, tubes: 11, extraTube: false, purity: 'flawless', k: 16, minutes: 5 }),
});
export const TIER_IDS = Object.freeze(Object.keys(TIERS));

const tierOf = (tier) => TIERS[tier] ?? TIERS.relaxed;

/** sizeForTier(tier) -> {colors, tubes} (unknown tiers read as Relaxed). */
export function sizeForTier(tier) {
  const t = tierOf(tier);
  return { colors: t.colors, tubes: t.tubes };
}

/** expectedMinutes(tier) -> about how long a board takes: 1 / 2 / 3 / 5. */
export function expectedMinutes(tier) {
  return tierOf(tier).minutes;
}

/** Whether the tier allows the one free extra tube (Relaxed only). */
export function extraTubeAllowed(tier) {
  return !!tierOf(tier).extraTube;
}

const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);
const top = (tube) => (tube.length ? tube[tube.length - 1] : null);

function topRun(tube) {
  if (!tube.length) return 0;
  const c = tube[tube.length - 1];
  let n = 0;
  for (let i = tube.length - 1; i >= 0 && tube[i] === c; i--) n++;
  return n;
}

const uniform = (tube) => tube.every((c) => c === tube[0]);

/** Pick `n` mutually distinguishable hexes: palette first, then a hue spread. */
function chooseColors(n, palette, rng) {
  const out = [];
  const fits = (hex, minDE) => out.every((h) => deltaEHex(h, hex) >= minDE);
  const norm = (h) => {
    try { return rgbToHex(hexToRgb(h)); } catch { return null; }
  };
  const pal = shuffle(rng, [...new Set((palette || []).map(norm).filter(Boolean))]);
  for (const minDE of [14, 10]) {
    for (const h of pal) if (out.length < n && !out.includes(h) && fits(h, minDE)) out.push(h);
  }
  // Fill with an even hue spread at alternating lightness.
  const offset = rng() * 360;
  const spread = [];
  for (let k = 0; k < 18; k++) {
    const L = [0.62, 0.78, 0.48][k % 3];
    spread.push(oklchToHex(clampToGamut({ L, C: 0.15, h: (offset + k * 47) % 360 })));
  }
  for (const minDE of [14, 10, 6, 0]) {
    for (const h of spread) if (out.length < n && !out.includes(h) && fits(h, minDE)) out.push(h);
  }
  return out.slice(0, n);
}

/** Legacy (v0.1): puzzle size for a batch worth `valueMinutes` minutes of production. Use sizeForTier. */
export function sizeForBatch(valueMinutes) {
  const v = Number.isFinite(valueMinutes) ? Math.max(0, valueMinutes) : 0;
  const steps = [5, 15, 30, 60, 120]; // thresholds in minutes
  let colors = MIN_COLORS;
  for (const s of steps) if (v >= s) colors++;
  colors = clamp(colors, MIN_COLORS, MAX_COLORS);
  return { colors, tubes: colors + 2 };
}

/** One random reverse pour; returns true if a move was made. */
function reversePour(tubes, capacity, rng) {
  const options = [];
  for (let a = 0; a < tubes.length; a++) {
    const A = tubes[a];
    if (!A.length) continue;
    const c = top(A);
    const run = topRun(A);
    for (let b = 0; b < tubes.length; b++) {
      if (b === a) continue;
      const B = tubes[b];
      const room = capacity - B.length;
      for (let k = 1; k <= Math.min(run, room); k++) {
        // Forward B -> A must be legal afterwards: A empty or still topped by c.
        // (Taking the whole run would expose a different color underneath.)
        if (k === run && k < A.length) continue;
        // Forward B -> A must move exactly k back.
        const runBAfter = k + (top(B) === c ? topRun(B) : 0);
        const freeAAfter = capacity - A.length + k;
        if (runBAfter !== k && freeAAfter !== k) continue;
        options.push([a, b, k]);
      }
    }
  }
  if (!options.length) return false;
  // Prefer single-unit moves so layers interleave.
  const singles = options.filter((o) => o[2] === 1);
  const [a, b, k] = singles.length && rng() < 0.6 ? pick(rng, singles) : pick(rng, options);
  const moved = tubes[a].splice(tubes[a].length - k, k);
  tubes[b].push(...moved);
  return true;
}

/**
 * create({tier?, colors = 4..9, tubes = colors + 2, capacity = 4, extraTube?}, rng, {palette}) -> puzzle
 * {tubes:[[colorIndex…]] bottom→top, capacity, colors:[hex], history:[], moves:0,
 *  extraTubeUsed:false, tier, extraTube}
 * With a `tier`, colors / tubes / extraTube come from TIERS (explicit numbers
 * still win). `extraTube` (default true without a tier) gates addTube.
 */
export function create(opts, rng, extra) {
  if (typeof rng !== 'function') throw new TypeError('purify.create: rng must be a function');
  const o = opts || {};
  const t = o.tier && TIERS[o.tier] ? TIERS[o.tier] : null;
  const nColors = clamp(Math.floor(o.colors || (t && t.colors) || MIN_COLORS), 2, 12);
  const capacity = Math.max(2, Math.floor(o.capacity || CAPACITY));
  const nTubes = Math.max(nColors + 1, Math.floor(o.tubes || (t && t.tubes) || nColors + 2));
  const colors = chooseColors(nColors, extra && extra.palette, rng);
  const allowExtra = typeof o.extraTube === 'boolean' ? o.extraTube : (t ? t.extraTube : true);

  const fresh = () => {
    const t = [];
    for (let i = 0; i < nTubes; i++) t.push(i < nColors ? new Array(capacity).fill(i) : []);
    return t;
  };
  const p = {
    tubes: fresh(), capacity, colors, history: [], moves: 0, extraTubeUsed: false,
    tier: t ? o.tier : null, extraTube: allowExtra,
  };
  // Mixed means some tube holds two colors (not merely a split color), so the
  // board never opens looking already sorted.
  const sorted = () => p.tubes.every((tube) => !tube.length || uniform(tube));
  const pours = 20 + nColors * 8;
  for (let attempt = 0; attempt < 20; attempt++) {
    for (let i = 0; i < pours; i++) reversePour(p.tubes, capacity, rng);
    if (!sorted()) break;
  }
  if (sorted()) {
    // Practically unreachable; keep pouring one at a time until mixed.
    for (let i = 0; i < 1000 && sorted(); i++) reversePour(p.tubes, capacity, rng);
  }
  return p;
}

/** createForTier(tier, rng, {palette}) -> a board sized and gated by TIERS[tier]. */
export function createForTier(tier, rng, extra) {
  return create({ tier: TIERS[tier] ? tier : 'relaxed' }, rng, extra);
}

/** True when a forward pour from -> to is allowed. */
export function canPour(p, from, to) {
  const A = p.tubes[from];
  const B = p.tubes[to];
  if (!A || !B || from === to || !A.length) return false;
  if (B.length >= p.capacity) return false;
  return !B.length || top(B) === top(A);
}

/** Pour the top run of `from` onto `to` (as much as fits). */
export function pour(p, from, to) {
  if (!canPour(p, from, to)) return { ok: false, moved: 0, completedTube: false, solved: isSolved(p) };
  const A = p.tubes[from];
  const B = p.tubes[to];
  const n = Math.min(topRun(A), p.capacity - B.length);
  B.push(...A.splice(A.length - n, n));
  p.history.push({ from, to, n });
  p.moves += 1;
  const completedTube = B.length === p.capacity && uniform(B);
  return { ok: true, moved: n, completedTube, solved: isSolved(p) };
}

/** Take back the last pour. Unlimited. Moves are not refunded (bragging only). */
export function undo(p) {
  const last = p.history.pop();
  if (!last) return { ok: false };
  const B = p.tubes[last.to];
  p.tubes[last.from].push(...B.splice(B.length - last.n, last.n));
  return { ok: true, from: last.to, to: last.from, moved: last.n };
}

/** Add the one free empty tube; only on a board whose tier allows it (Relaxed). */
export function addTube(p) {
  if (p.extraTubeUsed || p.extraTube === false) return { ok: false };
  p.tubes.push([]);
  p.extraTubeUsed = true;
  return { ok: true, index: p.tubes.length - 1 };
}

/** Solved when every non-empty tube holds a single color AND is full (corked). */
export function isSolved(p) {
  return p.tubes.every((t) => !t.length || (t.length === p.capacity && uniform(t)));
}

/** True when tube `i` is full and one color (it corks). */
export function isCorked(p, i) {
  const t = p.tubes[i];
  return !!t && t.length === p.capacity && uniform(t);
}

/** ARCHITECTURE.md shape: apply(p, {from, to} | {undo:true} | {addTube:true}). */
export function apply(p, move) {
  if (move && move.undo) {
    const r = undo(p);
    return { ...r, events: r.ok ? ['undo'] : ['refused'] };
  }
  if (move && move.addTube) {
    const r = addTube(p);
    return { ...r, events: r.ok ? ['tube'] : ['refused'] };
  }
  const r = pour(p, move && move.from, move && move.to);
  const events = r.ok ? ['pour', ...(r.completedTube ? ['cork'] : []), ...(r.solved ? ['solved'] : [])] : ['refused'];
  return { ...r, events };
}
