// purify.js — tube sort for muddy batches (pure, JSON-serializable state).
// Implements docs/DESIGN.md "Active play › Purifying (tube sort)" and
// ARCHITECTURE.md "Puzzles": 4 colors / 6 tubes up to 9 / 11 scaling with
// batch value, generated by REVERSE pours from a solved state so every
// puzzle is solvable; unlimited undo; one free extra tube (Relaxed).
//
// Tubes are arrays of color indices, bottom -> top. A forward pour moves the
// whole contiguous top run of the source as far as the target has room, onto
// an empty tube or a matching top color.
//
// Solvability: each reverse pour takes k units of color c off tube A and
// stacks them on tube B, and is only allowed when the matching forward pour
// B -> A is legal afterwards (A is empty or still topped by c) and moves
// exactly k units back (B's new top run is exactly k long, or A has exactly k
// free slots). Undoing the reverse pours in order therefore solves the puzzle.

import {
  hexToRgb, rgbToHex, oklchToHex, clampToGamut, deltaEHex,
} from '../color.js';
import { shuffle, pick } from '../rng.js';

export const MIN_COLORS = 4;
export const MAX_COLORS = 9;
export const CAPACITY = 4;

const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);
const top = (tube) => (tube.length ? tube[tube.length - 1] : null);

function topRun(tube) {
  if (!tube.length) return 0;
  const c = tube[tube.length - 1];
  let n = 0;
  for (let i = tube.length - 1; i >= 0 && tube[i] === c; i--) n++;
  return n;
}

const uniform = (tube) => tube.every((c) => c === tube[0]);

/** Pick `n` mutually distinguishable hexes: palette first, then a hue spread. */
function chooseColors(n, palette, rng) {
  const out = [];
  const fits = (hex, minDE) => out.every((h) => deltaEHex(h, hex) >= minDE);
  const norm = (h) => {
    try { return rgbToHex(hexToRgb(h)); } catch { return null; }
  };
  const pal = shuffle(rng, [...new Set((palette || []).map(norm).filter(Boolean))]);
  for (const minDE of [14, 10]) {
    for (const h of pal) if (out.length < n && !out.includes(h) && fits(h, minDE)) out.push(h);
  }
  // Fill with an even hue spread at alternating lightness.
  const offset = rng() * 360;
  const spread = [];
  for (let k = 0; k < 18; k++) {
    const L = [0.62, 0.78, 0.48][k % 3];
    spread.push(oklchToHex(clampToGamut({ L, C: 0.15, h: (offset + k * 47) % 360 })));
  }
  for (const minDE of [14, 10, 6, 0]) {
    for (const h of spread) if (out.length < n && !out.includes(h) && fits(h, minDE)) out.push(h);
  }
  return out.slice(0, n);
}

/** Puzzle size for a batch worth `valueMinutes` minutes of production. */
export function sizeForBatch(valueMinutes) {
  const v = Number.isFinite(valueMinutes) ? Math.max(0, valueMinutes) : 0;
  const steps = [5, 15, 30, 60, 120]; // thresholds in minutes
  let colors = MIN_COLORS;
  for (const s of steps) if (v >= s) colors++;
  colors = clamp(colors, MIN_COLORS, MAX_COLORS);
  return { colors, tubes: colors + 2 };
}

/** One random reverse pour; returns true if a move was made. */
function reversePour(tubes, capacity, rng) {
  const options = [];
  for (let a = 0; a < tubes.length; a++) {
    const A = tubes[a];
    if (!A.length) continue;
    const c = top(A);
    const run = topRun(A);
    for (let b = 0; b < tubes.length; b++) {
      if (b === a) continue;
      const B = tubes[b];
      const room = capacity - B.length;
      for (let k = 1; k <= Math.min(run, room); k++) {
        // Forward B -> A must be legal afterwards: A empty or still topped by c.
        // (Taking the whole run would expose a different color underneath.)
        if (k === run && k < A.length) continue;
        // Forward B -> A must move exactly k back.
        const runBAfter = k + (top(B) === c ? topRun(B) : 0);
        const freeAAfter = capacity - A.length + k;
        if (runBAfter !== k && freeAAfter !== k) continue;
        options.push([a, b, k]);
      }
    }
  }
  if (!options.length) return false;
  // Prefer single-unit moves so layers interleave.
  const singles = options.filter((o) => o[2] === 1);
  const [a, b, k] = singles.length && rng() < 0.6 ? pick(rng, singles) : pick(rng, options);
  const moved = tubes[a].splice(tubes[a].length - k, k);
  tubes[b].push(...moved);
  return true;
}

/**
 * create({colors = 4..9, tubes = colors + 2, capacity = 4}, rng, {palette}) -> puzzle
 * {tubes:[[colorIndex…]] bottom→top, capacity, colors:[hex], history:[], moves:0, extraTubeUsed:false}
 */
export function create(opts, rng, extra) {
  if (typeof rng !== 'function') throw new TypeError('purify.create: rng must be a function');
  const nColors = clamp(Math.floor((opts && opts.colors) || MIN_COLORS), 2, 12);
  const capacity = Math.max(2, Math.floor((opts && opts.capacity) || CAPACITY));
  const nTubes = Math.max(nColors + 1, Math.floor((opts && opts.tubes) || nColors + 2));
  const colors = chooseColors(nColors, extra && extra.palette, rng);

  const fresh = () => {
    const t = [];
    for (let i = 0; i < nTubes; i++) t.push(i < nColors ? new Array(capacity).fill(i) : []);
    return t;
  };
  const p = { tubes: fresh(), capacity, colors, history: [], moves: 0, extraTubeUsed: false };
  const pours = 20 + nColors * 8;
  for (let attempt = 0; attempt < 20; attempt++) {
    for (let i = 0; i < pours; i++) reversePour(p.tubes, capacity, rng);
    if (!isSolved(p)) break;
  }
  if (isSolved(p)) {
    // Practically unreachable; keep pouring one at a time until mixed.
    for (let i = 0; i < 1000 && isSolved(p); i++) reversePour(p.tubes, capacity, rng);
  }
  return p;
}

/** True when a forward pour from -> to is allowed. */
export function canPour(p, from, to) {
  const A = p.tubes[from];
  const B = p.tubes[to];
  if (!A || !B || from === to || !A.length) return false;
  if (B.length >= p.capacity) return false;
  return !B.length || top(B) === top(A);
}

/** Pour the top run of `from` onto `to` (as much as fits). */
export function pour(p, from, to) {
  if (!canPour(p, from, to)) return { ok: false, moved: 0, completedTube: false, solved: isSolved(p) };
  const A = p.tubes[from];
  const B = p.tubes[to];
  const n = Math.min(topRun(A), p.capacity - B.length);
  B.push(...A.splice(A.length - n, n));
  p.history.push({ from, to, n });
  p.moves += 1;
  const completedTube = B.length === p.capacity && uniform(B);
  return { ok: true, moved: n, completedTube, solved: isSolved(p) };
}

/** Take back the last pour. Unlimited. Moves are not refunded (bragging only). */
export function undo(p) {
  const last = p.history.pop();
  if (!last) return { ok: false };
  const B = p.tubes[last.to];
  p.tubes[last.from].push(...B.splice(B.length - last.n, last.n));
  return { ok: true, from: last.to, to: last.from, moved: last.n };
}

/** Add the one free empty tube (the caller gates this to Relaxed). */
export function addTube(p) {
  if (p.extraTubeUsed) return { ok: false };
  p.tubes.push([]);
  p.extraTubeUsed = true;
  return { ok: true, index: p.tubes.length - 1 };
}

/** Solved when every non-empty tube holds a single color. */
export function isSolved(p) {
  return p.tubes.every((t) => !t.length || uniform(t));
}

/** ARCHITECTURE.md shape: apply(p, {from, to} | {undo:true} | {addTube:true}). */
export function apply(p, move) {
  if (move && move.undo) {
    const r = undo(p);
    return { ...r, events: r.ok ? ['undo'] : ['refused'] };
  }
  if (move && move.addTube) {
    const r = addTube(p);
    return { ...r, events: r.ok ? ['tube'] : ['refused'] };
  }
  const r = pour(p, move && move.from, move && move.to);
  const events = r.ok ? ['pour', ...(r.completedTube ? ['cork'] : []), ...(r.solved ? ['solved'] : [])] : ['refused'];
  return { ...r, events };
}
