// catalog.js — GENERATED by tools/gen-catalog.js. Do not edit by hand:
// change the tables in the generator and run `node tools/gen-catalog.js --write`.
//
// The Era 1 swatch book (docs/DESIGN.md "Discovery and the catalog",
// "Catalog structure", "Economy › Color value") plus the eight weekly event
// pages ("Quests and weekly events › Weekly events").
//
// Contract (ARCHITECTURE.md "Content"):
//  - CATALOG: 100 Era 1 colors on PAGES (wheel 23, tints 22, shades 17, earths 22, wild 16).
//  - Mixable colors carry recipe [{pigment, weight}] (pigment ids from
//    pigments.js plus 'white'/'black') and hex === mixPaintHex(recipeParts(recipe)).
//  - Wild hues (page 'wild', foundBy 'hunt', region set) have recipe null and
//    cannot be mixed; sim discovery by mixing should only consider colors with
//    a recipe.
//  - Every pair of Era 1 colors is at least ERA1_MIN_DELTA_E (5) apart
//    (closest pair: sandstone / pistachio, ΔE 5.09); colors
//    on one event page are at least EVENT_MIN_DELTA_E (6) apart.
//  - EVENT_COLORS: 8 events x 12 ('<event-id>-1'..'-12'), recipe null.

import { pigmentHex } from './pigments.js';

export const ERA1_MIN_DELTA_E = 5;
export const EVENT_MIN_DELTA_E = 6;

/** Era 1 catalog pages in display order. */
export const PAGES = Object.freeze(['wheel', 'tints', 'shades', 'earths', 'wild']);

/** Base price in Coins per jar by tier (Era 1). */
export const TIER_PRICES = Object.freeze({ primary: 1, secondary: 3, tertiary: 8, tint: 15, wild: 60 });

/** Event ids in rotation order. */
export const EVENT_IDS = Object.freeze(['autumn-harvest', 'deep-sea', 'bloom-week', 'neon-night', 'winter-frost', 'festival-of-lanterns', 'golden-hour', 'ink-and-paper']);

const deepFreeze = (c) => {
  if (c.recipe) { c.recipe.forEach(Object.freeze); Object.freeze(c.recipe); }
  return Object.freeze(c);
};

/** The 100 Era 1 colors, page by page; order within a page is its position. */
export const CATALOG = Object.freeze([
  { id: 'mulberry', name: 'Mulberry', hex: '#824e52', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 2 }, { pigment: 'woad', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'red' },
  { id: 'rosewood', name: 'Rosewood', hex: '#975c5c', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 8 }, { pigment: 'woad', weight: 3 }, { pigment: 'white', weight: 2 }], foundBy: 'mix', hint: 'found by mixing', family: 'red' },
  { id: 'bunting-red', name: 'Bunting Red', hex: '#d65858', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'cochineal', weight: 2 }, { pigment: 'saffron', weight: 1 }, { pigment: 'white', weight: 1 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'red' },
  { id: 'brick-red', name: 'Brick Red', hex: '#b5615b', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 8 }, { pigment: 'woad', weight: 1 }, { pigment: 'white', weight: 3 }], foundBy: 'mix', hint: 'found by mixing', family: 'red' },
  { id: 'madder', name: 'Madder Red', hex: '#b8433a', era: 1, page: 'wheel', tier: 'primary', basePrice: 1, recipe: [{ pigment: 'madder', weight: 1 }], foundBy: 'start', hint: 'one of your first pigments', family: 'red' },
  { id: 'russet', name: 'Russet', hex: '#a65b39', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 5 }, { pigment: 'ochre', weight: 3 }, { pigment: 'white', weight: 1 }, { pigment: 'black', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'red' },
  { id: 'orange', name: 'Orange', hex: '#c56731', era: 1, page: 'wheel', tier: 'secondary', basePrice: 3, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'ochre', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'walnut', name: 'Walnut', hex: '#6f5c4c', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 4 }, { pigment: 'ochre', weight: 3 }, { pigment: 'woad', weight: 5 }, { pigment: 'black', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'marigold', name: 'Marigold', hex: '#cc7f2e', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'ochre', weight: 3 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'hazel', name: 'Hazel', hex: '#885d2f', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 3 }, { pigment: 'ochre', weight: 6 }, { pigment: 'woad', weight: 1 }, { pigment: 'black', weight: 2 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'ochre', name: 'Yellow Ochre', hex: '#d39b2a', era: 1, page: 'wheel', tier: 'primary', basePrice: 1, recipe: [{ pigment: 'ochre', weight: 1 }], foundBy: 'start', hint: 'one of your first pigments', family: 'yellow' },
  { id: 'olive', name: 'Olive', hex: '#8f8943', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'ochre', weight: 2 }, { pigment: 'woad', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'green', name: 'Green', hex: '#758054', era: 1, page: 'wheel', tier: 'secondary', basePrice: 3, recipe: [{ pigment: 'ochre', weight: 1 }, { pigment: 'woad', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'green' },
  { id: 'willow', name: 'Willow', hex: '#869473', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'ochre', weight: 4 }, { pigment: 'woad', weight: 5 }, { pigment: 'white', weight: 3 }], foundBy: 'mix', hint: 'found by mixing', family: 'green' },
  { id: 'spruce', name: 'Spruce', hex: '#62725f', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'ochre', weight: 3 }, { pigment: 'woad', weight: 5 }, { pigment: 'white', weight: 1 }, { pigment: 'black', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'green' },
  { id: 'juniper', name: 'Juniper', hex: '#68847e', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'ochre', weight: 3 }, { pigment: 'woad', weight: 8 }, { pigment: 'white', weight: 2 }], foundBy: 'mix', hint: 'found by mixing', family: 'teal' },
  { id: 'teal', name: 'Teal', hex: '#4d7181', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'ochre', weight: 1 }, { pigment: 'woad', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'blue' },
  { id: 'cornflower', name: 'Cornflower', hex: '#5983ae', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'woad', weight: 3 }, { pigment: 'white', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'blue' },
  { id: 'woad', name: 'Woad Blue', hex: '#3e6a9e', era: 1, page: 'wheel', tier: 'primary', basePrice: 1, recipe: [{ pigment: 'woad', weight: 1 }], foundBy: 'start', hint: 'one of your first pigments', family: 'blue' },
  { id: 'grand-spectrum', name: 'Grand Spectrum', hex: '#5574c1', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'lapis', weight: 2 }, { pigment: 'white', weight: 1 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'blue' },
  { id: 'violet', name: 'Violet', hex: '#5b5b73', era: 1, page: 'wheel', tier: 'secondary', basePrice: 3, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'woad', weight: 2 }], foundBy: 'mix', hint: 'found by mixing', family: 'violet' },
  { id: 'coronation-purple', name: 'Coronation Purple', hex: '#5a4b89', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'murex', weight: 3 }, { pigment: 'lapis', weight: 1 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'violet' },
  { id: 'mauve', name: 'Mauve', hex: '#7a636f', era: 1, page: 'wheel', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 3 }, { pigment: 'woad', weight: 3 }, { pigment: 'white', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'pink' },
  { id: 'quilt-patchwork', name: 'Patchwork Pink', hex: '#e298a5', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'cochineal', weight: 1 }, { pigment: 'chalk-white', weight: 3 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'pink' },
  { id: 'dusty-rose', name: 'Dusty Rose', hex: '#b79292', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 4 }, { pigment: 'woad', weight: 2 }, { pigment: 'white', weight: 7 }], foundBy: 'mix', hint: 'found by mixing', family: 'red' },
  { id: 'coral', name: 'Coral', hex: '#d0766c', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 4 }, { pigment: 'white', weight: 3 }], foundBy: 'grade', hint: 'found by grading', family: 'red' },
  { id: 'rose', name: 'Rose', hex: '#d78b80', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 4 }, { pigment: 'white', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'red' },
  { id: 'shell-pink', name: 'Shell Pink', hex: '#e5b6ab', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 3 }, { pigment: 'white', weight: 10 }], foundBy: 'grade', hint: 'found by grading', family: 'red' },
  { id: 'blush', name: 'Blush', hex: '#eacac0', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'white', weight: 6 }], foundBy: 'mix', hint: 'found by mixing', family: 'red' },
  { id: 'peach', name: 'Peach', hex: '#dda088', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 4 }, { pigment: 'ochre', weight: 1 }, { pigment: 'white', weight: 8 }], foundBy: 'grade', hint: 'found by grading', family: 'red' },
  { id: 'apricot', name: 'Apricot', hex: '#d69158', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 4 }, { pigment: 'ochre', weight: 5 }, { pigment: 'white', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'linen', name: 'Linen', hex: '#c5b19a', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'ochre', weight: 1 }, { pigment: 'woad', weight: 1 }, { pigment: 'white', weight: 5 }], foundBy: 'grade', hint: 'found by grading', family: 'orange' },
  { id: 'wheat', name: 'Wheat', hex: '#e1b279', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'ochre', weight: 2 }, { pigment: 'white', weight: 4 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'custard', name: 'Custard', hex: '#e7c691', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'ochre', weight: 3 }, { pigment: 'white', weight: 9 }], foundBy: 'grade', hint: 'found by grading', family: 'yellow' },
  { id: 'old-gold', name: 'Old Gold', hex: '#b38f3c', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'ochre', weight: 10 }, { pigment: 'woad', weight: 2 }, { pigment: 'white', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'lighthouse-white', name: 'Lighthouse White', hex: '#eee4c8', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'chalk-white', weight: 10 }, { pigment: 'saffron', weight: 1 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'yellow' },
  { id: 'sage', name: 'Sage', hex: '#c3c7ab', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'ochre', weight: 2 }, { pigment: 'woad', weight: 2 }, { pigment: 'white', weight: 9 }], foundBy: 'grade', hint: 'found by grading', family: 'yellow' },
  { id: 'kiln-glaze', name: 'Kiln Glaze', hex: '#9daa82', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'chalk-white', weight: 3 }, { pigment: 'lapis', weight: 2 }, { pigment: 'sulfur', weight: 3 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'green' },
  { id: 'sky-blue', name: 'Sky Blue', hex: '#8babc5', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'woad', weight: 3 }, { pigment: 'white', weight: 4 }], foundBy: 'mix', hint: 'found by mixing', family: 'blue' },
  { id: 'delft-blue', name: 'Delft Blue', hex: '#759abc', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'woad', weight: 5 }, { pigment: 'white', weight: 4 }], foundBy: 'grade', hint: 'found by grading', family: 'blue' },
  { id: 'loom-thread', name: 'Loom Thread', hex: '#b9a2b9', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'murex', weight: 1 }, { pigment: 'chalk-white', weight: 2 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'violet' },
  { id: 'ice', name: 'Ice', hex: '#d3ddde', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'woad', weight: 1 }, { pigment: 'white', weight: 8 }], foundBy: 'mix', hint: 'found by mixing', family: 'neutral' },
  { id: 'powder-blue', name: 'Powder Blue', hex: '#bccdd7', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'woad', weight: 1 }, { pigment: 'white', weight: 4 }], foundBy: 'grade', hint: 'found by grading', family: 'neutral' },
  { id: 'mist', name: 'Mist', hex: '#a2b5b1', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'ochre', weight: 1 }, { pigment: 'woad', weight: 3 }, { pigment: 'white', weight: 6 }], foundBy: 'mix', hint: 'found by mixing', family: 'neutral' },
  { id: 'eucalyptus', name: 'Eucalyptus', hex: '#88a09d', era: 1, page: 'tints', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'ochre', weight: 1 }, { pigment: 'woad', weight: 3 }, { pigment: 'white', weight: 3 }], foundBy: 'grade', hint: 'found by grading', family: 'neutral' },
  { id: 'stained-glass-ruby', name: 'Stained-Glass Ruby', hex: '#91253b', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'cochineal', weight: 4 }, { pigment: 'bone-black', weight: 1 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'pink' },
  { id: 'maroon', name: 'Maroon', hex: '#70342e', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 5 }, { pigment: 'black', weight: 2 }], foundBy: 'mix', hint: 'found by mixing', family: 'red' },
  { id: 'oxblood', name: 'Oxblood', hex: '#522c27', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 7 }, { pigment: 'black', weight: 6 }], foundBy: 'grade', hint: 'found by grading', family: 'red' },
  { id: 'rust', name: 'Rust', hex: '#934331', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 5 }, { pigment: 'ochre', weight: 1 }, { pigment: 'black', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'red' },
  { id: 'tobacco', name: 'Tobacco', hex: '#5d4323', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'ochre', weight: 3 }, { pigment: 'black', weight: 3 }], foundBy: 'grade', hint: 'found by grading', family: 'orange' },
  { id: 'bog-oak', name: 'Bog Oak', hex: '#40361d', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'ochre', weight: 3 }, { pigment: 'black', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'olive-drab', name: 'Olive Drab', hex: '#635629', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'ochre', weight: 5 }, { pigment: 'woad', weight: 1 }, { pigment: 'black', weight: 3 }], foundBy: 'grade', hint: 'found by grading', family: 'yellow' },
  { id: 'navy', name: 'Navy', hex: '#324961', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'woad', weight: 5 }, { pigment: 'black', weight: 2 }], foundBy: 'mix', hint: 'found by mixing', family: 'blue' },
  { id: 'storm-blue', name: 'Storm Blue', hex: '#38587c', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'woad', weight: 6 }, { pigment: 'black', weight: 1 }], foundBy: 'grade', hint: 'found by grading', family: 'blue' },
  { id: 'deep-fathom', name: 'Deep Fathom', hex: '#2f4b9d', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'lapis', weight: 3 }, { pigment: 'indigo', weight: 1 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'blue' },
  { id: 'atlas-ink', name: 'Atlas Ink', hex: '#2d3959', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'indigo', weight: 3 }, { pigment: 'bone-black', weight: 1 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'blue' },
  { id: 'damson', name: 'Damson', hex: '#614d57', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 5 }, { pigment: 'woad', weight: 5 }, { pigment: 'black', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'pink' },
  { id: 'bottle-green', name: 'Bottle Green', hex: '#4e645d', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'ochre', weight: 2 }, { pigment: 'woad', weight: 5 }, { pigment: 'black', weight: 1 }], foundBy: 'grade', hint: 'found by grading', family: 'neutral' },
  { id: 'forest', name: 'Forest', hex: '#38423d', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'ochre', weight: 2 }, { pigment: 'woad', weight: 5 }, { pigment: 'black', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'neutral' },
  { id: 'charcoal', name: 'Charcoal', hex: '#31333a', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'woad', weight: 3 }, { pigment: 'black', weight: 4 }], foundBy: 'grade', hint: 'found by grading', family: 'neutral' },
  { id: 'cocoa', name: 'Cocoa', hex: '#35261e', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'madder', weight: 2 }, { pigment: 'ochre', weight: 1 }, { pigment: 'black', weight: 7 }], foundBy: 'mix', hint: 'found by mixing', family: 'neutral' },
  { id: 'soot', name: 'Soot', hex: '#1e1f1f', era: 1, page: 'shades', tier: 'tint', basePrice: 15, recipe: [{ pigment: 'woad', weight: 1 }, { pigment: 'black', weight: 7 }], foundBy: 'grade', hint: 'found by grading', family: 'neutral' },
  { id: 'bramble', name: 'Bramble', hex: '#563d3f', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 5 }, { pigment: 'woad', weight: 2 }, { pigment: 'bone-black', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'pink' },
  { id: 'cinder-rose', name: 'Cinder Rose', hex: '#9d6f71', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 6 }, { pigment: 'woad', weight: 3 }, { pigment: 'chalk-white', weight: 4 }], foundBy: 'mix', hint: 'found by mixing', family: 'red' },
  { id: 'clay', name: 'Clay', hex: '#b3846c', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 2 }, { pigment: 'umber', weight: 3 }, { pigment: 'chalk-white', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'burnt-sienna', name: 'Burnt Sienna', hex: '#78492e', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 1 }, { pigment: 'umber', weight: 4 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'driftwood', name: 'Driftwood', hex: '#856d54', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 5 }, { pigment: 'woad', weight: 5 }, { pigment: 'sulfur', weight: 4 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'fawn', name: 'Fawn', hex: '#987c5c', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'white', weight: 1 }, { pigment: 'umber', weight: 4 }, { pigment: 'chalk-white', weight: 2 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'raw-sienna', name: 'Raw Sienna', hex: '#986d2c', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'ochre', weight: 4 }, { pigment: 'umber', weight: 5 }, { pigment: 'saffron', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'orange' },
  { id: 'tawny', name: 'Tawny', hex: '#ac7b2d', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'ochre', weight: 3 }, { pigment: 'umber', weight: 2 }, { pigment: 'saffron', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'tan', name: 'Tan', hex: '#b39871', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'umber', weight: 4 }, { pigment: 'chalk-white', weight: 6 }, { pigment: 'saffron', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'saffron-gold', name: 'Saffron Gold', hex: '#e5ab3b', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'sulfur', weight: 1 }, { pigment: 'saffron', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'sandstone', name: 'Sandstone', hex: '#bfa969', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'ochre', weight: 4 }, { pigment: 'black', weight: 1 }, { pigment: 'chalk-white', weight: 6 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'primrose', name: 'Primrose', hex: '#ecd889', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'white', weight: 3 }, { pigment: 'sulfur', weight: 1 }, { pigment: 'saffron', weight: 1 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'illuminated-gold', name: 'Illuminated Gold', hex: '#dbc13a', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'saffron', weight: 1 }, { pigment: 'sulfur', weight: 4 }], foundBy: 'commission', hint: 'a commission\'s signature color', family: 'yellow' },
  { id: 'turmeric', name: 'Turmeric', hex: '#c4b241', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'woad', weight: 1 }, { pigment: 'sulfur', weight: 6 }, { pigment: 'saffron', weight: 3 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'mustard', name: 'Mustard', hex: '#b2a23b', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'ochre', weight: 6 }, { pigment: 'woad', weight: 2 }, { pigment: 'sulfur', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'loden', name: 'Loden', hex: '#756d34', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'black', weight: 3 }, { pigment: 'chalk-white', weight: 1 }, { pigment: 'sulfur', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'lichen', name: 'Lichen', hex: '#c4c984', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'woad', weight: 1 }, { pigment: 'chalk-white', weight: 4 }, { pigment: 'sulfur', weight: 3 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'moss', name: 'Moss', hex: '#939c53', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'woad', weight: 3 }, { pigment: 'sulfur', weight: 4 }, { pigment: 'saffron', weight: 2 }], foundBy: 'mix', hint: 'found by mixing', family: 'yellow' },
  { id: 'pistachio', name: 'Pistachio', hex: '#aebb87', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'woad', weight: 2 }, { pigment: 'chalk-white', weight: 4 }, { pigment: 'sulfur', weight: 3 }], foundBy: 'mix', hint: 'found by mixing', family: 'green' },
  { id: 'taupe', name: 'Taupe', hex: '#9c888f', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 3 }, { pigment: 'woad', weight: 3 }, { pigment: 'chalk-white', weight: 5 }], foundBy: 'mix', hint: 'found by mixing', family: 'neutral' },
  { id: 'heather', name: 'Heather', hex: '#7f7685', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'madder', weight: 2 }, { pigment: 'woad', weight: 3 }, { pigment: 'chalk-white', weight: 2 }], foundBy: 'mix', hint: 'found by mixing', family: 'neutral' },
  { id: 'rosemary', name: 'Rosemary', hex: '#4c5244', era: 1, page: 'earths', tier: 'tertiary', basePrice: 8, recipe: [{ pigment: 'woad', weight: 5 }, { pigment: 'black', weight: 4 }, { pigment: 'saffron', weight: 4 }], foundBy: 'mix', hint: 'found by mixing', family: 'neutral' },
  { id: 'meadow-green', name: 'Meadow Green', hex: '#9ac12f', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'meadow', hint: 'a hunter\'s find on the Meadow', family: 'green' },
  { id: 'clover-pink', name: 'Clover Pink', hex: '#ea76ac', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'meadow', hint: 'a hunter\'s find on the Meadow', family: 'pink' },
  { id: 'honey-gold', name: 'Honey Gold', hex: '#ffb500', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'meadow', hint: 'a hunter\'s find on the Meadow', family: 'yellow' },
  { id: 'slate-grey', name: 'Slate Grey', hex: '#699499', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'quarry', hint: 'a hunter\'s find on the Quarry', family: 'teal' },
  { id: 'umber-brown', name: 'Umber Brown', hex: '#652f00', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'quarry', hint: 'a hunter\'s find on the Quarry', family: 'orange' },
  { id: 'ochre-rust', name: 'Ochre Rust', hex: '#873301', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'quarry', hint: 'a hunter\'s find on the Quarry', family: 'red' },
  { id: 'murex-purple', name: 'Murex Purple', hex: '#804497', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'coast', hint: 'a hunter\'s find on the Coast', family: 'violet' },
  { id: 'sea-glass', name: 'Sea Glass', hex: '#9fdcc6', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'coast', hint: 'a hunter\'s find on the Coast', family: 'teal' },
  { id: 'harbor-teal', name: 'Harbor Teal', hex: '#12807d', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'coast', hint: 'a hunter\'s find on the Coast', family: 'teal' },
  { id: 'cochineal-red', name: 'Cochineal Red', hex: '#b6194a', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'jungle', hint: 'a hunter\'s find on the Jungle', family: 'pink' },
  { id: 'parrot-green', name: 'Parrot Green', hex: '#27a343', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'jungle', hint: 'a hunter\'s find on the Jungle', family: 'green' },
  { id: 'orchid', name: 'Orchid', hex: '#bc71cb', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'jungle', hint: 'a hunter\'s find on the Jungle', family: 'violet' },
  { id: 'lava-red', name: 'Lava Red', hex: '#f05425', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'volcano', hint: 'a hunter\'s find on the Volcano', family: 'red' },
  { id: 'sulfur-yellow', name: 'Sulfur Yellow', hex: '#e7de1f', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'volcano', hint: 'a hunter\'s find on the Volcano', family: 'yellow' },
  { id: 'obsidian', name: 'Obsidian', hex: '#150f20', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'volcano', hint: 'a hunter\'s find on the Volcano', family: 'violet' },
  { id: 'ash-grey', name: 'Ash Grey', hex: '#c8b4c2', era: 1, page: 'wild', tier: 'wild', basePrice: 60, recipe: null, foundBy: 'hunt', region: 'volcano', hint: 'a hunter\'s find on the Volcano', family: 'neutral' },
].map(deepFreeze));

/** Limited event pages: 12 colors per event, rerun on the 8-week rotation. */
export const EVENT_COLORS = Object.freeze([
  { id: 'autumn-harvest-1', name: 'Harvest Gold', hex: '#e3ae28', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'yellow' },
  { id: 'autumn-harvest-2', name: 'Pumpkin', hex: '#e47600', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'orange' },
  { id: 'autumn-harvest-3', name: 'Russet Leaf', hex: '#b45b2e', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'orange' },
  { id: 'autumn-harvest-4', name: 'Cider', hex: '#cc9140', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'orange' },
  { id: 'autumn-harvest-5', name: 'Maple Red', hex: '#a92227', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'red' },
  { id: 'autumn-harvest-6', name: 'Acorn', hex: '#7c5828', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'orange' },
  { id: 'autumn-harvest-7', name: 'Amber Glow', hex: '#c16f00', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'orange' },
  { id: 'autumn-harvest-8', name: 'Bramble Jam', hex: '#5b2036', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'pink' },
  { id: 'autumn-harvest-9', name: 'Wheat Sheaf', hex: '#eed59b', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'yellow' },
  { id: 'autumn-harvest-10', name: 'Orchard Apple', hex: '#ce5053', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'red' },
  { id: 'autumn-harvest-11', name: 'Pear Skin', hex: '#b9bf5f', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'yellow' },
  { id: 'autumn-harvest-12', name: 'Chestnut', hex: '#60311e', era: 1, page: 'event', event: 'autumn-harvest', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Autumn Harvest', family: 'red' },
  { id: 'deep-sea-1', name: 'Pearl', hex: '#efebe0', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'neutral' },
  { id: 'deep-sea-2', name: 'Abalone', hex: '#a1c5cc', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'teal' },
  { id: 'deep-sea-3', name: 'Lagoon', hex: '#31a5a5', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'teal' },
  { id: 'deep-sea-4', name: 'Fathom Teal', hex: '#076b6f', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'teal' },
  { id: 'deep-sea-5', name: 'Kelp', hex: '#526c43', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'green' },
  { id: 'deep-sea-6', name: 'Abyss', hex: '#12253c', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'blue' },
  { id: 'deep-sea-7', name: 'Squid Ink', hex: '#15151f', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'neutral' },
  { id: 'deep-sea-8', name: 'Coral Reef', hex: '#e1897e', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'red' },
  { id: 'deep-sea-9', name: 'Spindrift', hex: '#b9e6d9', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'teal' },
  { id: 'deep-sea-10', name: 'Nautilus', hex: '#5c869f', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'blue' },
  { id: 'deep-sea-11', name: 'Tidepool', hex: '#2b8d71', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'green' },
  { id: 'deep-sea-12', name: 'Anemone', hex: '#ae6aa8', era: 1, page: 'event', event: 'deep-sea', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Deep Sea', family: 'pink' },
  { id: 'bloom-week-1', name: 'Peony', hex: '#eb90b9', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'pink' },
  { id: 'bloom-week-2', name: 'Lilac Spray', hex: '#c1a3d8', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'violet' },
  { id: 'bloom-week-3', name: 'Sweet Pea', hex: '#e7c0de', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'pink' },
  { id: 'bloom-week-4', name: 'Fresh Fern', hex: '#65a64d', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'green' },
  { id: 'bloom-week-5', name: 'New Leaf', hex: '#b7d978', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'green' },
  { id: 'bloom-week-6', name: 'Tulip Red', hex: '#cf4047', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'red' },
  { id: 'bloom-week-7', name: 'Wisteria', hex: '#947fc1', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'violet' },
  { id: 'bloom-week-8', name: 'Rosebud', hex: '#d0557f', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'pink' },
  { id: 'bloom-week-9', name: 'Daffodil', hex: '#f2dd5a', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'yellow' },
  { id: 'bloom-week-10', name: 'Bluebell', hex: '#656cba', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'blue' },
  { id: 'bloom-week-11', name: 'Stem Green', hex: '#3f713a', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'green' },
  { id: 'bloom-week-12', name: 'Apple Blossom', hex: '#f9dbe6', era: 1, page: 'event', event: 'bloom-week', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Bloom Week', family: 'pink' },
  { id: 'neon-night-1', name: 'Electric Pink', hex: '#f92da2', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'pink' },
  { id: 'neon-night-2', name: 'Laser Lime', hex: '#b0f42f', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'green' },
  { id: 'neon-night-3', name: 'Neon Tangerine', hex: '#fe7802', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'orange' },
  { id: 'neon-night-4', name: 'Hot Magenta', hex: '#d00aca', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'violet' },
  { id: 'neon-night-5', name: 'Volt Yellow', hex: '#fdf720', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'yellow' },
  { id: 'neon-night-6', name: 'Cyber Cyan', hex: '#2eeded', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'teal' },
  { id: 'neon-night-7', name: 'Ultraviolet', hex: '#7523de', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'violet' },
  { id: 'neon-night-8', name: 'Signal Red', hex: '#ea2221', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'red' },
  { id: 'neon-night-9', name: 'Glow Green', hex: '#39e252', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'green' },
  { id: 'neon-night-10', name: 'Arc Blue', hex: '#1874ed', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'blue' },
  { id: 'neon-night-11', name: 'Midnight Neon', hex: '#191731', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'violet' },
  { id: 'neon-night-12', name: 'Arcade Purple', hex: '#6b139e', era: 1, page: 'event', event: 'neon-night', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Neon Night', family: 'violet' },
  { id: 'winter-frost-1', name: 'First Snow', hex: '#f7f5ef', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'neutral' },
  { id: 'winter-frost-2', name: 'Rime', hex: '#d3e8f7', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'blue' },
  { id: 'winter-frost-3', name: 'Glacier', hex: '#70bdde', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'blue' },
  { id: 'winter-frost-4', name: 'Silver Birch', hex: '#bbbec1', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'neutral' },
  { id: 'winter-frost-5', name: 'Pewter Sky', hex: '#81878d', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'neutral' },
  { id: 'winter-frost-6', name: 'Steel Blue', hex: '#50799b', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'blue' },
  { id: 'winter-frost-7', name: 'Icicle', hex: '#9ee4dd', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'teal' },
  { id: 'winter-frost-8', name: 'Northern Sky', hex: '#5aa0d0', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'blue' },
  { id: 'winter-frost-9', name: 'Midwinter', hex: '#2c3d5d', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'blue' },
  { id: 'winter-frost-10', name: 'Hoarfrost', hex: '#9da8be', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'blue' },
  { id: 'winter-frost-11', name: 'Aurora Teal', hex: '#53bcac', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'teal' },
  { id: 'winter-frost-12', name: 'Frozen Lake', hex: '#3d6473', era: 1, page: 'event', event: 'winter-frost', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Winter Frost', family: 'teal' },
  { id: 'festival-of-lanterns-1', name: 'Lantern Orange', hex: '#f3821d', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'orange' },
  { id: 'festival-of-lanterns-2', name: 'Paper Red', hex: '#d33c33', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'red' },
  { id: 'festival-of-lanterns-3', name: 'Candle Glow', hex: '#f8c970', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'yellow' },
  { id: 'festival-of-lanterns-4', name: 'Ember', hex: '#a03313', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'red' },
  { id: 'festival-of-lanterns-5', name: 'Firecracker', hex: '#eb5200', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'red' },
  { id: 'festival-of-lanterns-6', name: 'Marigold Garland', hex: '#fba62a', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'orange' },
  { id: 'festival-of-lanterns-7', name: 'Silk Crimson', hex: '#9d1133', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'red' },
  { id: 'festival-of-lanterns-8', name: 'Tassel Gold', hex: '#c8a83a', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'yellow' },
  { id: 'festival-of-lanterns-9', name: 'Lacquer', hex: '#6b1e1c', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'red' },
  { id: 'festival-of-lanterns-10', name: 'Sunset Pink', hex: '#e7768a', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'pink' },
  { id: 'festival-of-lanterns-11', name: 'Night Lantern', hex: '#3a1e0e', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'orange' },
  { id: 'festival-of-lanterns-12', name: 'Paper Moon', hex: '#f5e7c3', era: 1, page: 'event', event: 'festival-of-lanterns', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Festival of Lanterns', family: 'yellow' },
  { id: 'golden-hour-1', name: 'Peach Glow', hex: '#f4bd99', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'orange' },
  { id: 'golden-hour-2', name: 'Honey Light', hex: '#eab444', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'yellow' },
  { id: 'golden-hour-3', name: 'Dusk Violet', hex: '#725b9a', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'violet' },
  { id: 'golden-hour-4', name: 'Lavender Haze', hex: '#ae9ece', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'violet' },
  { id: 'golden-hour-5', name: 'Apricot Sky', hex: '#e3975a', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'orange' },
  { id: 'golden-hour-6', name: 'Rose Gold', hex: '#cb8c81', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'red' },
  { id: 'golden-hour-7', name: 'Long Shadow', hex: '#423b65', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'violet' },
  { id: 'golden-hour-8', name: 'Amber Field', hex: '#cd8817', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'orange' },
  { id: 'golden-hour-9', name: 'Mauve Cloud', hex: '#a47692', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'pink' },
  { id: 'golden-hour-10', name: 'Golden Wheat', hex: '#f1d680', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'yellow' },
  { id: 'golden-hour-11', name: 'Afterglow', hex: '#d66643', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'red' },
  { id: 'golden-hour-12', name: 'Twilight Blue', hex: '#42558a', era: 1, page: 'event', event: 'golden-hour', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Golden Hour', family: 'blue' },
  { id: 'ink-and-paper-1', name: 'Vellum', hex: '#f1ebd9', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'neutral' },
  { id: 'ink-and-paper-2', name: 'Parchment', hex: '#e2cead', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'yellow' },
  { id: 'ink-and-paper-3', name: 'Sepia Ink', hex: '#6a4b2f', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'orange' },
  { id: 'ink-and-paper-4', name: 'Iron Gall', hex: '#222f3c', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'neutral' },
  { id: 'ink-and-paper-5', name: 'Lamp Black', hex: '#171614', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'neutral' },
  { id: 'ink-and-paper-6', name: 'Indigo Ink', hex: '#243163', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'blue' },
  { id: 'ink-and-paper-7', name: 'Walnut Ink', hex: '#533525', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'orange' },
  { id: 'ink-and-paper-8', name: 'Faded Ink', hex: '#6a7586', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'neutral' },
  { id: 'ink-and-paper-9', name: 'Rubric Red', hex: '#a8372e', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'red' },
  { id: 'ink-and-paper-10', name: 'Quill Grey', hex: '#9b9893', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'neutral' },
  { id: 'ink-and-paper-11', name: 'Oak Gall', hex: '#7a6548', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'yellow' },
  { id: 'ink-and-paper-12', name: 'Lapis Wash', hex: '#5a78bc', era: 1, page: 'event', event: 'ink-and-paper', tier: 'tint', basePrice: 15, recipe: null, foundBy: 'event', hint: 'an event color from Ink and Paper', family: 'blue' },
].map(deepFreeze));

const BY_ID = new Map([...CATALOG, ...EVENT_COLORS].map((c) => [c.id, c]));

/** Era 1 colors grouped by page: { wheel: Color[], tints, shades, earths, wild }. */
export const COLORS_BY_PAGE = Object.freeze(Object.fromEntries(
  PAGES.map((p) => [p, Object.freeze(CATALOG.filter((c) => c.page === p))]),
));

/** Event colors grouped by event id. */
export const EVENT_COLORS_BY_EVENT = Object.freeze(Object.fromEntries(
  EVENT_IDS.map((e) => [e, Object.freeze(EVENT_COLORS.filter((c) => c.event === e))]),
));

/** Any catalog or event color by id, or undefined. */
export function getColor(id) {
  return BY_ID.get(id);
}

/** Era 1 colors that have a recipe (everything except wild hues). */
export function mixableColors() {
  return CATALOG.filter((c) => c.recipe);
}

/** A recipe as mixPaint parts: [{pigment, weight}] -> [{hex, weight}]. */
export function recipeParts(recipe) {
  return recipe.map((p) => ({ hex: pigmentHex(p.pigment), weight: p.weight }));
}
