#!/usr/bin/env node
// Tincture — tools/bump-version.js
//
//   node tools/bump-version.js <semver>        e.g. 0.1.1
//   node tools/bump-version.js <semver> --touch   also refresh the build timestamp
//
// Rewrites, in one go, every place the shipped version lives:
//   src/version.js   export const APP_VERSION = '<semver>';
//   src/app.js       the same line, only if app.js happens to declare its own
//   version.json     {"version","build"}
//   sw.js            CACHE_VERSION and the SHELL precache list
//
// SHELL is regenerated by globbing (no dependencies): './', index.html,
// style.css, manifest.webmanifest, version.json, every file in icons/, and every
// .js under src/ (recursive). Run it whenever shipped files are added, removed
// or changed. It is idempotent: re-running with the same version and the same
// files changes nothing (the build timestamp is kept unless --touch is given
// or the version changes).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const version = args.find((a) => !a.startsWith('--'));
const touch = args.includes('--touch');

if (!version || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)) {
  console.error('usage: node tools/bump-version.js <semver>   (e.g. 0.1.1)');
  process.exit(1);
}

const abs = (...p) => path.join(ROOT, ...p);
const read = (p) => fs.readFileSync(abs(p), 'utf8');
const write = (p, s) => { if (!fs.existsSync(abs(p)) || read(p) !== s) fs.writeFileSync(abs(p), s); };

function walk(dir, filter) {
  const out = [];
  if (!fs.existsSync(abs(dir))) return out;
  for (const e of fs.readdirSync(abs(dir), { withFileTypes: true })) {
    const rel = dir + '/' + e.name;
    if (e.isDirectory()) out.push(...walk(rel, filter));
    else if (filter(e.name)) out.push(rel);
  }
  return out;
}

// --- src/version.js -------------------------------------------------------
write('src/version.js', `/**
 * version.js: the single source of the shipped app version.
 *
 * Owned by tools/bump-version.js, which rewrites this line together with
 * version.json and the CACHE_VERSION + SHELL list in sw.js. Lives here (not in
 * app.js) so pwa.js, settings.js and app.js can all import it.
 */
export const APP_VERSION = '${version}';
`);

// --- src/app.js (only if it declares its own constant) ----------------------
if (fs.existsSync(abs('src/app.js'))) {
  const app = read('src/app.js');
  const next = app.replace(/(const APP_VERSION\s*=\s*)(['"])[^'"]*\2/, `$1'${version}'`);
  if (next !== app) write('src/app.js', next);
}

// --- version.json -----------------------------------------------------------
let build = new Date().toISOString();
if (fs.existsSync(abs('version.json'))) {
  try {
    const prev = JSON.parse(read('version.json'));
    if (prev.version === version && prev.build && !touch) build = prev.build;
  } catch (e) { /* rewrite below */ }
}
write('version.json', JSON.stringify({ version, build }) + '\n');

// --- sw.js ------------------------------------------------------------------
const shell = [
  './',
  'index.html',
  'style.css',
  'manifest.webmanifest',
  'version.json',
  ...walk('icons', () => true).sort(),
  ...walk('src', (n) => n.endsWith('.js')).sort(),
].filter((f) => f === './' || fs.existsSync(abs(f)));

let sw = read('sw.js');
const verRe = /var CACHE_VERSION = '[^']*';/;
const shellRe = /var SHELL = \[[\s\S]*?\n\];/;
if (!verRe.test(sw) || !shellRe.test(sw)) {
  console.error('sw.js is missing the CACHE_VERSION or SHELL block; refusing to rewrite.');
  process.exit(1);
}
sw = sw
  .replace(verRe, `var CACHE_VERSION = '${version}';`)
  .replace(shellRe, () => 'var SHELL = [\n' + shell.map((f) => `  '${f}'`).join(',\n') + '\n];');
write('sw.js', sw);

console.log(`Tincture ${version}: ${shell.length} files in the SHELL list.`);
